replicas: 1

application:
  djangoSecret: "Secret value"
  byteCode: "1"
  bufferCode: "1"

image:
  registry: ""
  repository: todo
  pullPolicy: IfNotPresent
  tag: latest

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port:
    podPort: 8080
    nodePort: 30100

automountServiceAccountToken: true
horizontalPodAutoscaler:
  enabled: false
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

storageClassName: "microk8s-hostpath"

livenessProbe:
  httpGet:
    path: /api/status
    port: 8080
  failureThreshold: 5
  periodSeconds: 60
  initialDelaySeconds: 5
readinessProbe:
  httpGet:
    path: /api/status
    port: 8080
  failureThreshold: 5
  periodSeconds: 60
  initialDelaySeconds: 5
startupProbe:
  httpGet:
    path: /api/status
    port: 8080
  failureThreshold: 5
  periodSeconds: 60
  initialDelaySeconds: 5