apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django-todo.fullname" . }}
  labels:
    {{- include "django-todo.labels" . | nindent 4}}
data:
  PYTHONDONTWRITEBYTECODE: "1"
  PYTHONUNBUFFERED: "1"