apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo.fullname" . }}
  labels:
    {{- include "todo.labels" . | nindent 4}}
data:
  PYTHONDONTWRITEBYTECODE: {{ .Values.application.byteCode | quote }}
  PYTHONUNBUFFERED: {{ .Values.application.bufferCode | quote }}