apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo.fullname" . }}
  labels:
    {{- include "todo.labels" . | nindent 4}}
stringData:
  djangoSecret: {{ .Values.application.djangoSecret }}
  