apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-todo.fullname" . }}
  labels:
    {{- include "django-todo.labels" . | nindent 4}}
stringData:
  djangoSecret: "django-insecure--1*s6izyo7ckr%8lg27@^88)hzyp$1(ojj6=y5p$%6m-bp5-%w"
  