# Generated by Django 4.2.6 on 2023-10-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='update_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
