name: Check Checklist

on:
  pull_request_review:
    types: [submitted, requested_changes, dismissed]

jobs:
  check-checklist:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_review'
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.18'
          
      - name: Install build dependencies 
        run: sudo apt-get install -y python3-dev libssl-dev libffi-dev

      - name: Install dependencies
        run: pip install -r .github/scripts/requirements.txt

      - name: Run checklist check
        run: python .github/scripts/check_checklist.py
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.inputs.pr_number || github.event.pull_request.number }}
