name: Check Checklist

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull request number'
        required: true
  pull_request:
    types: [opened, synchronize, reopened, closed]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]

jobs:
  check-checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install build dependencies 
        run: sudo apt-get install -y python3-dev libssl-dev libffi-dev

      - name: Install dependencies
        run: pip install -r .github/scripts/requirements.txt

      - name: Run checklist check
        run: python .github/scripts/check_checklist.py
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.inputs.pr_number || github.event.pull_request.number }}
